/**
 * SvgIcon component for rendering SVG icons from the sprite system
 *
 * Uses <svg><use href> for efficient icon rendering from the generated sprite.
 * Falls back to document.svg if the icon doesn't exist.
 */

import { type CSSProperties, memo } from "react";

export interface SvgIconProps {
  /**
   * Icon name without the prefix.
   * Examples:
   * - Dev icons: "typescript-typescript-original" (folder-name format)
   * - Filetypes: "document", "rust", "typescript"
   * - UI icons: "ic_copy", "ic_folder"
   */
  name: string;
  /** Size in pixels (width and height) */
  size?: number;
  /** Additional CSS classes */
  className?: string;
  /** Icon color (CSS color value) - only works for single-color icons */
  color?: string;
  /** Whether to apply currentColor (inherits text color) */
  currentColor?: boolean;
  /** Custom styles */
  style?: CSSProperties;
  /** Accessible label for screen readers (replaces alt from img-based icons) */
  alt?: string;
}

/**
 * Renders an SVG icon from the sprite sheet using <use href>
 *
 * The sprite is generated by vite-plugin-svg-icons and injected into the DOM.
 * Symbol IDs follow the format: icon-{dir}-{name} or icon-{name}
 */
export const SvgIcon = memo(function SvgIcon({
  name,
  size = 16,
  className = "",
  color,
  currentColor,
  style,
  alt,
}: SvgIconProps) {
  const symbolId = `#icon-${name}`;

  // Auto-detect UI icons (they start with "ic_") and use currentColor for them
  // UI icons are monochrome and should inherit text color for dark theme compatibility
  const isUiIcon = name.startsWith("ic_");
  const shouldUseCurrentColor = currentColor ?? isUiIcon;

  // Determine fill color
  const fill = shouldUseCurrentColor ? "currentColor" : color;

  return (
    <svg
      width={size}
      height={size}
      className={`inline-block shrink-0 ${className}`}
      style={style}
      aria-hidden={!alt}
      aria-label={alt}
      role={alt ? "img" : undefined}
    >
      <use href={symbolId} fill={fill} />
    </svg>
  );
});

export default SvgIcon;

/**
 * Helper to get icon name from a file path
 * @param category - "dev_icons" | "filetypes" | "ui"
 * @param path - Path within the category (e.g., "typescript/typescript-original" or "document")
 * @returns The symbol name to pass to SvgIcon
 */
export function getIconName(category: "dev_icons" | "filetypes" | "ui", path: string): string {
  // Remove .svg extension if present
  const cleanPath = path.replace(/\.svg$/, "");

  // For dev_icons, the path includes folder/name, which maps to folder-name
  // For filetypes/ui, it's just the name
  if (category === "dev_icons") {
    // Convert "typescript/typescript-original" to "typescript-typescript-original"
    return cleanPath.replace(/\//g, "-");
  }

  return cleanPath;
}
